#!/bin/bash
#CREADOR Henry Chumo | 06/06/2019
# UPDATE DEFINIDO    | 26/10/2023
# MODIFICADO         | MgScript

# NUNCA  DEJES DE APRENDER
# POWER BY MgScript

# -*- ENCODING: UTF-8 -*-
z="
";XUz='MgScript|MgScript|MgScript'
